title: NHG Office of Human Research Protection Programme (OHRPP)
url: https://ethics.gri.nhg.com.sg
favicon: /images/Logo/favicon-isomer.ico
colors:
  primary-color: "#21409a"
  secondary-color: "#00828d"
  media-colors:
    - title: media-color-one
      color: "#00828d"
    - title: media-color-two
      color: "#d2232a"
    - title: media-color-three
      color: "#d2232a"
    - title: media-color-four
      color: "#8d000f"
    - title: media-color-five
      color: "#00828d"
description: A National Healthcare Group (NHG) site built with Isomer
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d3klp0713m5tta.amplifyapp.com
prod: https://master.d2xg4pfdtrypjl.amplifyapp.com
facebook-pixel: ""
shareicon: /images/OHRPP Logo/favicon-isomer.ico
is_government: false
google_analytics_ga4: G-PK950Z6NG6
linkedin-insights: ""
resources_name: newsroom
